### PR TITLE
Add the possibility to use seeds when generating a did document

### PR DESCRIPTION
**Pull request by GabrielKidane**
Created a map of purpose to seed which will be used if available by cryptold to create a deterministic keypair.

### CODE REVIEW

**Comment by GabrielKidane** [comment]
@dmitrizagidulin I'm unable to add you as reviewer so I've tagged you. I've added the option to pass in seeds per key purpose as this is something I currently require and it might be an useful feature for others.

**Comment by dmitrizagidulin** [comment]
Thanks @GabrielKidane!
My main question is - I get the convenience of having deterministic seeds for the various keys, but why not generate them from seeds beforehand, and put them into the key map? (That's exactly what it's there for).

**Comment by GabrielKidane96** [comment]
After mulling it over, I can see what you mean. Therefore this PR is no longer necessary and can be removed.

**Comment by dmitrizagidulin** [comment]
@GabrielKidane thanks again, cheers.

**Comment by GabrielKidane** [comment]
I do think that it is not clear from the documentation that such a thing is possible. Might be a good thing to have an example of it.

**Comment by dmitrizagidulin** [comment]
> I do think that it is not clear from the documentation that such a thing is possible. Might be a good thing to have an example of it.

Good idea, thanks.

**Pull request closed without merging**
